server:
  port: 8085

spring:
  application:
    name: company-service

  datasource:
    url: jdbc:postgresql://${DB_URL}/postgres
    username: ${USERNAME}
    password: ${PASSWORD}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show-sql: true
logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log